name: Emergency Module CI

on: push
  
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build test executable
        run: gcc -std=c11 -Wall -Wextra -pthread emergency_module.c tester/test.c -o test_runner

      - name: Run tests
        run: ./test_runner
