name: Emergency Module CI

on:
  push:
  pull_request:

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gcc
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Build test executable
        run: gcc -std=c11 -Wall -Wextra -pthread emergency_module.c tests/test.c -o test_runner

      - name: Run tests
        run: ./test_runner
